
<div class="content" >


    <form id="validation_demo" action=""> 

        <!-- Third / Half column-->
        <div class="widgets">
            <div class="oneThree">
                <div class="profileSetting" >
                    <div class="avartar"><img src="/images/avartarB.jpg" width="180" height="180" alt="avatar" /></div>
                    <div class="avartar">
                        <input type="file" class="fileupload" />
                    </div>
                </div>
                <hr/>
            </div>

            <div class="twoOne">
               

                <div class="section ">
                    <label> Nombre <small>Text custom</small></label>   
                    <div> 
                        <input type="text" class="validate[required] large" name="f_required" id="f_required">
                    </div>
                </div>
                <div class="section ">
                    <label> Apellido Paterno <small>Text custom</small></label>   
                    <div> 
                        <input type="text" class="validate[required] large" name="f_required" id="f_required">
                    </div>
                </div>
                <div class="section ">
                    <label> Apellido materno <small>Text custom</small></label>   
                    <div> 
                        <input type="text" class="validate[required] large" name="f_required" id="f_required">
                    </div>
                </div>
               
                <div class="section ">
                    <label>Sexo<small></small></label>   
                    <div> 
                        <div>
                            <input type="radio" name="opinions" id="radio-1" value="1"  class="ck"/>
                            <label for="radio-1">Hombre</label>
                        </div>
                        <div>
                            <input type="radio" name="opinions" id="radio-2" value="1"  class="ck"  checked="checked"/>
                            <label for="radio-2" >Mujer</label>
                        </div>
                    </div>
                </div>
                <div class="section ">
                    <label> Email<small>Correo electronico</small></label>   
                    <div> 
                        <input type="text" class="validate[required,custom[email]]  large" name="e_required" id="e_required">
                    </div>
                </div>
                <div class="section ">
                    <label> telefono<small>numeor telefonico/small></label>   
                    <div> 
                        <input type="text" class="validate[required]  large" name="e_required" id="phone">
                    </div>
                </div>


                <div class="section last">
                    <div>
                        <a class="uibutton submit_form" >submitForm</a>
                    </div>
                </div>

            </div>

        </div><!-- End Third / Half column-->

    </form>

    <!-- clear fix -->
    <div class="clear"></div>

</div><!-- End content -->