<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

    <head>

        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
        <meta name="description" content=""/>
        <meta name="keywords" content=""/>

        <title>Control escolar</title>

        <!-- Link shortcut icon-->
        <link rel="shortcut icon" type="image/ico" href="/images/favicon2.ico"/> 

        <!-- Link css-->
        <link rel="stylesheet" type="text/css" href="/css/zice.style.css"/>
        <link rel="stylesheet" type="text/css" href="/css/icon.css"/>
        <link rel="stylesheet" type="text/css" href="/css/ui-custom.css"/>
        <link rel="stylesheet" type="text/css" href="/css/timepicker.css"/>
        <link rel="stylesheet" type="text/css" href="/components/colorpicker/css/colorpicker.css"/>
        <link rel="stylesheet" type="text/css" href="/components/elfinder/css/elfinder.css"/>
        <link rel="stylesheet" type="text/css" href="/components/datatables/dataTables.css"/>
        <link rel="stylesheet" type="text/css" href="/components/validationEngine/validationEngine.jquery.css"/>     
        <link rel="stylesheet" type="text/css" href="/components/jscrollpane/jscrollpane.css"/>
        <link rel="stylesheet" type="text/css" href="/components/fancybox/jquery.fancybox.css"/>
        <link rel="stylesheet" type="text/css" href="/components/tipsy/tipsy.css"/>
        <link rel="stylesheet" type="text/css" href="//components/editor/jquery.cleditor.css"/>
        <link rel="stylesheet" type="text/css" href="/components/chosen/chosen.css"/>
        <link rel="stylesheet" type="text/css" href="/components/confirm/jquery.confirm.css"/>
        <link rel="stylesheet" type="text/css" href="/components/sourcerer/sourcerer.css"/>
        <link rel="stylesheet" type="text/css" href="/components/fullcalendar/fullcalendar.css"/>
        <link rel="stylesheet" type="text/css" href="/components/Jcrop/jquery.Jcrop.css"/>   

<!--[if lte IE 8]><script language="javascript" type="text/javascript" src="components/flot/excanvas.min.js"></script><![endif]-->  

        <script type="text/javascript" src="/js/jquery.min.js"></script>
        <script type="text/javascript" src="/components/ui/jquery.ui.min.js"></script> 
        <script type="text/javascript" src="/components/ui/jquery.autotab.js"></script>
        <script type="text/javascript" src="/components/ui/timepicker.js"></script>
        <script type="text/javascript" src="/components/colorpicker/js/colorpicker.js"></script>
        <script type="text/javascript" src="/components/checkboxes/iphone.check.js"></script>
        <script type="text/javascript" src="/components/elfinder/js/elfinder.full.js"></script>
        <script type="text/javascript" src="/components/datatables/dataTables.min.js"></script>
        <script type="text/javascript" src="/components/datatables/ColVis.js"></script>
        <script type="text/javascript" src="/components/scrolltop/scrolltopcontrol.js"></script>
        <script type="text/javascript" src="/components/fancybox/jquery.fancybox.js"></script>
        <script type="text/javascript" src="/components/jscrollpane/mousewheel.js"></script>
        <script type="text/javascript" src="/components/jscrollpane/mwheelIntent.js"></script>
        <script type="text/javascript" src="/components/jscrollpane/jscrollpane.min.js"></script>
        <script type="text/javascript" src="/components/spinner/ui.spinner.js"></script>
        <script type="text/javascript" src="/components/tipsy/jquery.tipsy.js"></script>
        <script type="text/javascript" src="/components/editor/jquery.cleditor.js"></script>
        <script type="text/javascript" src="/components/chosen/chosen.js"></script>
        <script type="text/javascript" src="/components/confirm/jquery.confirm.js"></script>
        <script type="text/javascript" src="/components/validationEngine/jquery.validationEngine.js"></script>
        <script type="text/javascript" src="/components/validationEngine/jquery.validationEngine-en.js"></script>
        <script type="text/javascript" src="/components/vticker/jquery.vticker-min.js"></script>
        <script type="text/javascript" src="/components/sourcerer/sourcerer.js"></script>
        <script type="text/javascript" src="/components/fullcalendar/fullcalendar.js"></script>
        <script type="text/javascript" src="//components/flot/flot.js"></script>
        <script type="text/javascript" src="/components/flot/flot.pie.min.js"></script>
        <script type="text/javascript" src="/components/flot/flot.resize.min.js"></script>
        <script type="text/javascript" src="/components/flot/graphtable.js"></script>
        <script type="text/javascript" src="/components/uploadify/swfobject.js"></script>
        <script type="text/javascript" src="/components/uploadify/uploadify.js"></script>        
        <script type="text/javascript" src="/components/checkboxes/customInput.jquery.js"></script>
        <script type="text/javascript" src="/components/effect/jquery-jrumble.js"></script>
        <script type="text/javascript" src="/components/filestyle/jquery.filestyle.js"></script>
        <script type="text/javascript" src="/components/placeholder/jquery.placeholder.js"></script>
        <script type="text/javascript" src="/components/Jcrop/jquery.Jcrop.js"></script>
        <script type="text/javascript" src="/components/imgTransform/jquery.transform.js"></script>
        <script type="text/javascript" src="/components/webcam/webcam.js"></script>
        <script type="text/javascript" src="/components/rating_star/rating_star.js"></script>
        <script type="text/javascript" src="/components/dualListBox/dualListBox.js"></script>
        <script type="text/javascript" src="/components/smartWizard/jquery.smartWizard.min.js"></script>
        <script type="text/javascript" src="/components/maskedinput/jquery.maskedinput.js"></script>
        <script type="text/javascript" src="/components/highlightText/highlightText.js"></script>
        <script type="text/javascript" src="/components/elastic/jquery.elastic.source.js"></script>
        <script type="text/javascript" src="/js/jquery.cookie.js"></script>
        <script type="text/javascript" src="/js/zice.custom.js"></script>    
    


    </head>        
    <body class="dashborad">        
        <div id="alertMessage" class="error"></div>
        <!-- Header -->
        <div id="header">
            <div id="account_info"> 
                <img src="/images/avatar.png" alt="Online" class="avatar"/>
                <div class="setting" title="Opciones"><b>Bienvenido,</b> <b class="red">Usuario</b><img src="/images/gear.png" class="gear"  alt="Profile Setting" ></div>
                <div class="logout" title="Desconectar"><b >Salir</b> <img src="/images/connect.png" name="connect" class="disconnect" alt="disconnect" ></div> 
            </div>
        </div><!-- End Header -->
        <div id="shadowhead"></div>
 
        <div id="left_menu">
            <ul id="main_menu" class="main_menu">
                <li id="inicio" class="limenu"><a href="dashboard.html"><span class="ico gray shadow home" ></span><b>Inicio</b></a></li>
                <li id="alumnos" class="limenu" ><a href="#" ><span class="ico gray shadow window"></span><b>Alumnos</b></a>
                    <ul>
                        <li ><a href="/alumnos/index/registrar">Registrar</a></li>
                        <li ><a href="vform.html"> Buscar</a></li>

                    </ul>
                </li>
                <li class="limenu" ><a href="#"><span class="ico gray  dimensions" ></span><b>Procesos</b></a>
                    <ul>
                        <li ><a href="profile.html"> Inscripcion</a></li>
                        <li ><a href="conversation.html"> Reescripcion</a></li>
                    </ul>
                </li>
                <li class="limenu" ><a href="#"><span class="ico gray  dimensions" ></span><b>Materias</b></a>
                    <ul>
                        <li ><a href="profile.html"> Registrar</a></li>
                        <li ><a href="conversation.html">Buscar</a></li>
                        <li ><a href="conversation.html">Asignarr</a></li>
                    </ul>
                </li>



            </ul>
        </div>


        <div id="content">
            <div class="inner">
                <div class="topcolumn">
                    <div class="logo"></div>
                    <ul  id="shortcut">
                        <li> <a href="#" title="Back To home"> <img src="/images/icon/shortcut/home.png" alt="home"/><strong>Inicio</strong> </a> </li>
<!--                                <li> <a href="#" title="Website Graph"> <img src="/images/icon/shortcut/graph.png" alt="graph"/><strong>Graph</strong> </a> </li>
                        <li> <a href="#" title="Setting" > <img src="/images/icon/shortcut/setting.png" alt="setting" /><strong>Setting</strong></a> </li> 
                        <li> <a href="#" title="Messages"> <img src="/images/icon/shortcut/mail.png" alt="messages" /><strong>Message</strong></a><div class="notification" >10</div></li>-->
                    </ul>
                    <div class="clear"></div>
                </div>
                <div class="clear"></div>

                <!-- full width -->
                <!--                    <div class="widget">-->
                <?php echo $this->layout()->content; ?>
                <!--                    </div> End full width -->

                <!-- full width -->



                <!-- clear fix -->
                <div class="clear"></div>

                <div id="footer"> &copy; Copyright 2012 <span class="tip"><a  href="#" title="Zice Admin" >blabla</a> </span> </div>

            </div> <!--// End inner -->
        </div> <!--// End content --> 
    </body>
</html>